version: '3.5'

services:
  mysql-prod:
    image: mysql/mysql-server:5.7.21
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kwetter
      - MYSQL_USER=kwetter
      - MYSQL_PASSWORD=12345678

  payara-prod:
    build: .
    ports:
      - "8888:8080"
      - "4949:4848"
    links:
      - mysql
    depends_on:
      - mysql