version: '3.5'

services:
  mysql-dev:
    image: mysql/mysql-server:5.7.21
    ports:
      - "3307:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kwetter
      - MYSQL_USER=kwetter
      - MYSQL_PASSWORD=12345678

  payara-dev:
    build: .
    ports:
      - "8181:8080"
      - "4848:4848"
    links:
      - mysql-dev
    depends_on:
      - mysql-dev